// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChH1-0RwtXCWqfqO4ABgMwd6HU31DK2PI',
    appId: '1:1001608364832:web:03a10fe980e1103eb7cd45',
    messagingSenderId: '1001608364832',
    projectId: 'examencmovil',
    authDomain: 'examencmovil.firebaseapp.com',
    storageBucket: 'examencmovil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2YoJofH9jHqR2Uk2GkBGG4g9FbH0zP4',
    appId: '1:1001608364832:android:729cb92a2c52e800b7cd45',
    messagingSenderId: '1001608364832',
    projectId: 'examencmovil',
    storageBucket: 'examencmovil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpu5GgZG_C7tdJvah_Gfu8-kUGOHdicqI',
    appId: '1:1001608364832:ios:0f35b2aae83a5978b7cd45',
    messagingSenderId: '1001608364832',
    projectId: 'examencmovil',
    storageBucket: 'examencmovil.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpu5GgZG_C7tdJvah_Gfu8-kUGOHdicqI',
    appId: '1:1001608364832:ios:0f35b2aae83a5978b7cd45',
    messagingSenderId: '1001608364832',
    projectId: 'examencmovil',
    storageBucket: 'examencmovil.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChH1-0RwtXCWqfqO4ABgMwd6HU31DK2PI',
    appId: '1:1001608364832:web:908cbb5bc4902003b7cd45',
    messagingSenderId: '1001608364832',
    projectId: 'examencmovil',
    authDomain: 'examencmovil.firebaseapp.com',
    storageBucket: 'examencmovil.firebasestorage.app',
  );
}
